[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
target-version = "py37"  
# lint.select = ["E", "F", "W", "I"]
lint.ignore = ["E741", ]
