name: Ruff Linting

on:
  push:
    branches: [ dev-lint]
  # No pull_request trigger to avoid running on PRs

jobs:
  ruff:
    name: Lint with Ruff
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install ruff
        
    - name: Run Ruff linter
      run: ruff check .
        
    - name: Run Ruff formatter check
      run: ruff format --check .
      
    - name: Upload diagnostic info on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ruff-diagnostics
        path: |
          pyproject.toml
          .pre-commit-config.yaml